name: build-base-image

on:
  push:
    paths:
      - "infra/Dockerfile"
      - ".github/workflows/docker-base.yml"
  pull_request:
    paths:
      - "infra/Dockerfile"
  workflow_dispatch:        # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write        # push to GHCR
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/Dockerfile
          push: true
          build-args: |
            ESG_BASE_VERSION=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/esg-base:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/esg-base:latest
